[package]
name = "snarkvm"
version = "0.8.0"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "A decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkVM"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography::cryptocurrencies", "operating-systems" ]
include = [ "Cargo.toml", "snarkvm", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2018"

[workspace]
members = [
  "algorithms",
  "circuits",
  "curves",
  "derives",
  "dpc",
  "fields",
  "gadgets",
  "marlin",
  "parameters",
  "polycommit",
  "profiler",
  "r1cs",
  "utilities",
  "wasm",
  ".integration"
]

[lib]
path = "snarkvm/lib.rs"

[[bin]]
name = "snarkvm"
path = "snarkvm/cli/main.rs"
required-features = [ "cli" ]

[features]
default = [ "core" ]
core = [ "dpc", "utilities" ]
full = [
  "algorithms",
  "curves",
  "dpc",
  "fields",
  "gadgets",
  "parameters",
  "r1cs",
  "utilities"
]
algorithms = [ "snarkvm-algorithms" ]
curves = [ "snarkvm-curves" ]
dpc = [ "snarkvm-dpc" ]
fields = [ "snarkvm-fields" ]
gadgets = [ "snarkvm-gadgets" ]
parameters = [ "snarkvm-parameters" ]
r1cs = [ "snarkvm-r1cs" ]
utilities = [ "snarkvm-utilities" ]
cuda = [ "snarkvm-algorithms/cuda" ]
parameters_no_std_out = [ "snarkvm-parameters/no_std_out" ]
cli = [ "anyhow", "colored", "self_update", "structopt", "thiserror" ]
noconfig = [ ]

[dependencies.snarkvm-algorithms]
path = "./algorithms"
version = "0.8.0"
optional = true

[dependencies.snarkvm-curves]
path = "./curves"
version = "0.8.0"
optional = true

[dependencies.snarkvm-dpc]
path = "./dpc"
version = "0.8.0"
optional = true

[dependencies.snarkvm-fields]
path = "./fields"
version = "0.8.0"
optional = true

[dependencies.snarkvm-gadgets]
path = "./gadgets"
version = "0.8.0"
optional = true

[dependencies.snarkvm-parameters]
path = "./parameters"
version = "0.8.0"
optional = true

[dependencies.snarkvm-r1cs]
path = "./r1cs"
version = "0.8.0"
optional = true

[dependencies.snarkvm-utilities]
path = "./utilities"
version = "0.8.0"
optional = true

[dependencies.anyhow]
version = "1.0.53"
optional = true

[dependencies.colored]
version = "2"
optional = true

[dependencies.self_update]
version = "0.28"
optional = true

[dependencies.structopt]
version = "0.3"
optional = true

[dependencies.thiserror]
version = "1.0"
optional = true

[dev-dependencies.rusty-hook]
version = "0.11.2"

[profile.release]
opt-level = 3
lto = "thin"
incremental = true

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = "thin"
incremental = true
debug-assertions = false

[profile.dev]
opt-level = 0
incremental = true

[profile.test]
opt-level = 3
lto = "thin"
incremental = true
debug = true
debug-assertions = true
